apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: lab5-fastapi
data:
  APP_ENV: "учебный"
  APP_VERSION: "1.0.0"
  config.js: |
    window.APP_CONFIG = {
      APP_TITLE: "Лабораторная работа 5: FastAPI и Kubernetes",
      API_BASE_URL: ""
    };